env = { ZDOTDIR = "/Users/jurvistest/.config/zsh" }

[shell]
args = ["-l"]
program = "/bin/zsh"

[font]
size = 16.0

[colors.primary]
background = '#f7f7f7'
foreground = '#000000'

[colors.cursor]
text = '#f7f7f7'
cursor = '#000000'

[colors.normal]
black = '#000000'
red = '#aa3731'
green = '#448c27'
yellow = '#cb9000'
blue = '#325cc0'
magenta = '#7a3e9d'
cyan = '#0083b2'
white = '#bbbbbb'

[colors.bright]
black = '#777777'
red = '#f05050'
green = '#60cb00'
yellow = '#ffbc5d'
blue = '#007acc'
magenta = '#e64ce6'
cyan = '#00aacb'
white = '#ffffff'
